# Generated by Django 6.0.4 on 2026-09-16 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenge', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='something',
            old_name='name',
            new_name='text',
        ),
    ]
